keyrenewperiod: "0"

resources:
  requests:
    cpu: "2m"
    memory: "100Mi"
  limits:
    cpu: "10m"
    memory: "120Mi"

metrics:
  serviceMonitor:
    enabled: true 
    labels:
      release: smf-prometheus 


